# Generated by Django 5.1.7 on 2025-04-30 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Must be a user with role_id = 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, help_text='Only staff or superuser can onboard other users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
