# Generated by Django 5.1.7 on 2025-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinfo',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
