# Generated by Django 5.1.7 on 2025-05-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0005_tempuser_latitude_tempuser_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinfo',
            name='update_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
