# Generated by Django 5.1.7 on 2025-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authservice', '0008_userfinancialinfo_update_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernomineeinfo',
            name='update_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
