# Generated by Django 5.1.7 on 2025-04-28 18:18

import assetservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('age_in_months', models.PositiveIntegerField(help_text='Age in months')),
                ('color', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=6, null=True)),
                ('vaccination_status', models.CharField(choices=[('vaccinated', 'Vaccinated'), ('not_vaccinated', 'Not Vaccinated')], max_length=20)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('deworming_status', models.CharField(choices=[('dewormed', 'Dewormed'), ('not_dewormed', 'Not Dewormed')], max_length=20)),
                ('last_deworming_date', models.DateField(blank=True, null=True)),
                ('special_mark', models.TextField(blank=True, null=True)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('muzzle_video', models.FileField(blank=True, null=True, upload_to=assetservice.models.asset_upload_path)),
                ('left_side_image', models.ImageField(blank=True, null=True, upload_to=assetservice.models.asset_upload_path)),
                ('right_side_image', models.ImageField(blank=True, null=True, upload_to=assetservice.models.asset_upload_path)),
                ('challan_paper', models.FileField(blank=True, null=True, upload_to=assetservice.models.asset_upload_path)),
                ('vet_certificate', models.FileField(blank=True, null=True, upload_to=assetservice.models.asset_upload_path)),
                ('chairman_certificate', models.FileField(blank=True, null=True, upload_to=assetservice.models.asset_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
