# Generated by Django 5.1.7 on 2025-04-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0003_assethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_id_from',
            field=models.TextField(blank=True, null=True),
        ),
    ]
