# Generated by Django 5.1.7 on 2025-04-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0004_asset_asset_id_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_id_from',
            new_name='asset_id_from_ai_service',
        ),
    ]
