# Generated by Django 5.1.7 on 2025-05-08 05:56

import assetservice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0006_breed_color_dewormingstatus_mediatype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='chairman_certificate',
            field=models.FileField(default=1, upload_to=assetservice.models.asset_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='challan_paper',
            field=models.FileField(default=1, upload_to=assetservice.models.asset_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='left_side_image',
            field=models.ImageField(default=1, upload_to=assetservice.models.asset_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='muzzle_video',
            field=models.FileField(default=1, upload_to=assetservice.models.asset_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='refernce_id',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='right_side_image',
            field=models.ImageField(default=1, upload_to=assetservice.models.asset_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='vet_certificate',
            field=models.FileField(default=1, upload_to=assetservice.models.asset_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='health_issues',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='special_mark',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight in kilograms', max_digits=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AssetMedia',
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
    ]
