# Generated by Django 5.1.7 on 2025-05-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetservice', '0007_asset_chairman_certificate_asset_challan_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='refernce_id',
            field=models.TextField(unique=True),
        ),
    ]
