# Generated by Django 5.1.7 on 2025-04-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='amount_claimed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
